/**
 * Repositório central de consultas SQL (extraídas dos arquivos .jrxml).
 */
const Queries = {
    // 1. ficha_Parceiro_Grow.jrxml (Principal)
    getFichaPrincipal: (codparc) => `
SELECT TGFPAR.CODPARC
     , TGFPAR.NOMEPARC
     , 'Cód.Grow: ' || TGFPAR.CODPARC ||', Cód.Arte: ' || NVL(TGFPAR.CODARTE,0) || ', Cód.Uai: ' || NVL(TGFPAR.CODUAI,0) ||', Cód.Fest: ' || NVL(TGFPAR.CODFEST,0) AS CODERP
     , FORMATAR_CPF_CNPJ(TGFPAR.CGCCPF) AS CGC_CPF
     , RTRIM(LTRIM(UPPER(TGFPAR.LOGRADOURO ||' '|| TGFPAR.NUMEND || ' '|| TGFPAR.COMPLEMENTO || ' ' ||TGFPAR.BAIRRO))) AS ENDERECO
     , RTRIM(LTRIM(UPPER(TSICID.NOMECID || ' - ' || TSICID.UF))) AS CIDADE
     , TGFPAR.TELEFONE
     , TGFPAR.CELULAR
     , TGFPAR.EMAIL
     , TGFPAR.DTNASC
     , TO_CHAR(NVL(TGFPAR.DESCONTO_CONTRATO,0))AS AD_PERCONTRATODESCONTO
     , TGFPAR.DTCAD
     , (SELECT MAX(DTALTER)
        FROM(
        SELECT TRUNC(MAX(DTALTER))AS DTALTER
          FROM MOTOPRD.AD_PARLIMHIST
         WHERE CODPARC IN (SELECT CODARTE FROM TABLE(GROWPRD.AD_GET_PARCEIROS_ERP(TGFPAR.CODPARC)))
        UNION ALL
        SELECT TRUNC(MAX(DTALTER)) AS DTALTER
          FROM RAJAPRD.AD_PARLIMHIST
         WHERE CODPARC IN (SELECT CODUAI FROM TABLE(GROWPRD.AD_GET_PARCEIROS_ERP(TGFPAR.CODPARC)))
        )SUB) AS ULT_ANA_CREDITO
     ,  (SELECT TIPNEG
           FROM (
               SELECT TPV.CODTIPVENDA || ' - ' || TPV.DESCRTIPVENDA AS TIPNEG
                 FROM GROWPRD.TGFCAB CAB
               INNER JOIN GROWPRD.TGFTPV TPV ON CAB.CODTIPVENDA = TPV.CODTIPVENDA
               WHERE CAB.CODPARC = ${codparc}
        )  SUB
        GROUP BY TIPNEG
        ORDER BY COUNT(1) DESC
        FETCH FIRST ROW ONLY) AS TIPNEG_1
    , (SELECT TIPOTIT
         FROM(
            SELECT TIT.CODTIPTIT || ' - ' || TIT.DESCRTIPTIT AS TIPOTIT
              FROM MOTOPRD.TGFFIN FIN
              INNER JOIN MOTOPRD.TGFTIT TIT ON FIN.CODTIPTIT = TIT.CODTIPTIT
             WHERE FIN.CODTIPOPER = 901
               AND FIN.CODPARC IN (SELECT CODARTE FROM TABLE(GROWPRD.AD_GET_PARCEIROS_ERP(${codparc})))
            UNION ALL
            SELECT TIT.CODTIPTIT || ' - ' || TIT.DESCRTIPTIT AS TIPOTIT
              FROM RAJAPRD.TGFFIN FIN
              INNER JOIN RAJAPRD.TGFTIT TIT ON FIN.CODTIPTIT = TIT.CODTIPTIT
             WHERE FIN.CODTIPOPER = 901
               AND FIN.CODPARC IN (SELECT CODUAI FROM TABLE(GROWPRD.AD_GET_PARCEIROS_ERP(${codparc})))
        )SUB
        GROUP BY TIPOTIT
        ORDER BY COUNT(1) DESC
        FETCH FIRST ROW ONLY) AS TIPOTIT_1
      , (SELECT MAX(DTNEG)
           FROM(
        SELECT MAX(DTNEG) AS DTNEG
           FROM GROWPRD.TGFCAB CAB
          WHERE CAB.CODPARC = ${codparc}
            AND (CAB.NUPEDFEST IS NOT NULL OR CAB.NUPEDUAI IS NOT NULL OR CAB.NUPEDARTE IS NOT NULL)
        )SUB)  AS ULT_CONTATO
      , NULL AS PARC_MATRIZ
      , CAST(NVL(TGFPAR.LIMCREDITO,0) AS FLOAT) AS LIMCRED
      , NVL(GROWPRD.AD_GET_LIM_CRED_DISPONIVEL(TGFPAR.CODPARC),0) AS LIMITE_DISP
      , (SELECT COUNT(1)
          FROM(
              SELECT DISTINCT NURENEG
               FROM MOTOPRD.TGFFIN
              WHERE CODPARC IN (SELECT CODARTE FROM TABLE(GROWPRD.AD_GET_PARCEIROS_ERP(${codparc}))) AND RECDESP = 1 AND DHBAIXA IS NULL AND NURENEG IS NOT NULL
              UNION ALL
              SELECT DISTINCT NURENEG
               FROM RAJAPRD.TGFFIN
              WHERE CODPARC IN (SELECT CODUAI FROM TABLE(GROWPRD.AD_GET_PARCEIROS_ERP(${codparc}))) AND RECDESP = 1 AND DHBAIXA IS NULL AND NURENEG IS NOT NULL
          )SUB ) AS QTD_RENEG
      , CAST(NVL(
                (SELECT SUM(VLRLIQUIDO)
                   FROM(
                    SELECT SUM(VLRLIQUIDO) AS VLRLIQUIDO
                      FROM MOTOPRD.VGFFIN
                    WHERE CODPARC IN (SELECT CODARTE FROM TABLE(GROWPRD.AD_GET_PARCEIROS_ERP(${codparc}))) AND RECDESP = 1 AND DHBAIXA IS NULL AND DTVENC < SYSDATE AND CODTIPTIT = 4
                    UNION ALL
                    SELECT SUM(VLRLIQUIDO) AS VLRLIQUIDO
                      FROM RAJAPRD.VGFFIN
                    WHERE CODPARC IN (SELECT CODUAI FROM TABLE(GROWPRD.AD_GET_PARCEIROS_ERP(${codparc}))) AND RECDESP = 1 AND DHBAIXA IS NULL AND DTVENC < SYSDATE AND CODTIPTIT = 4
                    UNION ALL
                    SELECT SUM(VALOR) AS VLRLIQUIDO
                      FROM GROWPRD.TGFFIN
                    WHERE CODPARC = ${codparc}
                      AND VENCIDO = 'S'
                      AND FORMARECEBIMENTO <> 'DINHEIRO'
                )SUB),0)AS FLOAT) TIT_EM_ATRASO
      , CAST(NVL(
                (SELECT SUM(VLRLIQUIDO)
                   FROM(
                    SELECT SUM(VLRLIQUIDO) AS VLRLIQUIDO
                      FROM MOTOPRD.VGFFIN
                      INNER JOIN MOTOPRD.TGFTIT TIT ON ( TIT.CODTIPTIT =  VGFFIN.CODTIPTIT AND AD_TIPVENDA = 1)
                    WHERE CODPARC IN (SELECT CODARTE FROM TABLE(GROWPRD.AD_GET_PARCEIROS_ERP(${codparc}))) AND RECDESP = 1 AND DHBAIXA IS NULL AND DTVENC >= SYSDATE
                    UNION ALL
                    SELECT SUM(VLRLIQUIDO) AS VLRLIQUIDO
                      FROM RAJAPRD.VGFFIN
                      INNER JOIN RAJAPRD.TGFTIT TIT ON ( TIT.CODTIPTIT =  VGFFIN.CODTIPTIT AND AD_TIPVENDA = 1)
                    WHERE CODPARC IN (SELECT CODUAI FROM TABLE(GROWPRD.AD_GET_PARCEIROS_ERP(${codparc}))) AND RECDESP = 1 AND DHBAIXA IS NULL AND DTVENC >= SYSDATE
                    UNION ALL
                    SELECT SUM(VALOR) AS VLRLIQUIDO
                      FROM GROWPRD.TGFFIN
                    WHERE CODPARC = ${codparc}
                      AND VENCIDO = 'N'
                )SUB),0)AS FLOAT) AS TIT_EM_ABERTO
        , SPC.DET_SPC AS SPC
        , CAST(SPC.SITUACAO AS FLOAT) AS COLOR_SPC
        , SPC.OBSERVACAO AS OBS_SPC
        , CAST(nvl(GROWPRD.AD_GET_CREDITO_CLIENTE(${codparc}, 9),0) AS FLOAT) AS VLRCRED_ARTE
        , CAST(nvl(GROWPRD.AD_GET_CREDITO_CLIENTE(${codparc}, 1),0) AS FLOAT) AS VLRCRED_UAI
        , CAST(nvl(GROWPRD.AD_GET_CREDITO_CLIENTE(${codparc}, 50),0) AS FLOAT) AS VLRCRED_FEST
        , CASE WHEN NVL(TGFPAR.SIMPLES,'N') = 'S' THEN 'Sim' ELSE 'Não' END SIMPLES
        , TGFPAR.DESCRICAOIE AS CLASSIFICMS
        , (SELECT PAR.MOTBLOQ
              FROM MOTOPRD.TGFPAR PAR
              WHERE PAR.CODPARC IN (SELECT CODARTE FROM TABLE(GROWPRD.AD_GET_PARCEIROS_ERP(${codparc})))
                AND PAR.MOTBLOQ IS NOT NULL
                AND ROWNUM = 1
        ) AS MOTBLOQ
        , (SELECT PAR.AD_HISTORICOCREDITOMOTOFEST
              FROM MOTOPRD.TGFPAR PAR
              WHERE PAR.CODPARC IN (SELECT CODARTE FROM TABLE(GROWPRD.AD_GET_PARCEIROS_ERP(${codparc})))
                AND PAR.AD_HISTORICOCREDITOMOTOFEST IS NOT NULL
                AND ROWNUM = 1
        ) AS HIST_FEST
        , NVL((SELECT SUM(VLRDESDOB)
              FROM(
                    SELECT FIN.VLRDESDOB
                      FROM MOTOPRD.TGFFIN FIN
                     WHERE (FIN.CODCTABCOINT = 27)
                       AND (FIN.CODPARC IN (SELECT CODARTE FROM TABLE(GROWPRD.AD_GET_PARCEIROS_ERP(${codparc}))))
                       AND (FIN.RECDESP = 1)
                    UNION ALL
                    SELECT FIN.VLRDESDOB
                      FROM RAJAPRD.TGFFIN FIN
                     WHERE (FIN.CODCTABCOINT = 71)
                       AND (FIN.CODPARC IN (SELECT CODUAI FROM TABLE(GROWPRD.AD_GET_PARCEIROS_ERP(${codparc}))))
                       AND (FIN.RECDESP = 1)
            )SUB ),0) AS VLR_PCLD
          , CAST(NVL((SELECT COUNT(1) FROM GROWPRD.PARCTT CTT WHERE CTT.CODPARC = TGFPAR.CODPARC),0) AS FLOAT) QTD_CTT
          , ROUND(NVL (
               (SELECT AVG (GREATEST (NVL (DHBAIXA, SYSDATE) - DTVENC, 0))
                  FROM(
                  SELECT F.DHBAIXA,F.DTVENC FROM MOTOPRD.TGFFIN F
                 WHERE F.CODPARC IN (SELECT CODARTE FROM TABLE(GROWPRD.AD_GET_PARCEIROS_ERP(${codparc})))
                       AND F.CODTIPTIT = 4 AND F.PROVISAO = 'N' AND F.RECDESP = 1 AND F.DTVENC >= SYSDATE - 180
                UNION ALL
                  SELECT F.DHBAIXA,F.DTVENC FROM RAJAPRD.TGFFIN F
                 WHERE F.CODPARC IN (SELECT CODUAI FROM TABLE(GROWPRD.AD_GET_PARCEIROS_ERP(${codparc})))
                       AND F.CODTIPTIT = 4 AND F.PROVISAO = 'N' AND F.RECDESP = 1 AND F.DTVENC >= SYSDATE - 180
                  UNION ALL
                       SELECT NULL AS DHBAIXA, F.DTVENC FROM GROWPRD.TGFFIN F
                         WHERE F.CODPARC = ${codparc} AND F.DTVENC >= SYSDATE - 180
                  UNION ALL
                       SELECT F.DTMOV AS DHBAIXA, F.DTVENC FROM MOTOPRD.AD_FESTFIN_RECEBIDO F
                         WHERE F.CODPARC IN (SELECT CODARTE FROM TABLE(GROWPRD.AD_GET_PARCEIROS_ERP(${codparc}))) AND F.DTVENC >= SYSDATE - 180
            )SUB), 0),2)
               AS ATR_MEDIO_DIAS
    FROM GROWPRD.TGFPAR
   LEFT JOIN GROWPRD.TSICID ON TSICID.CODCID = TGFPAR.CODCID
   OUTER APPLY (SELECT DECODE(SUB.SITUACAO,'1','Com Pendências','0', 'Sem Pendências','2','Com Pend. Desconsideradas') || CASE WHEN SUB.SITUACAO = '1' THEN   ' - Data: ' || DATA || ', Qtd.: ' || NVL(SUB.QTDPENDENCIA,0) || ', Vlr.: R$ ' || NVL(SUB.VLRPENDENCIA,0)  ELSE '. Data Últ. Consulta: ' || TO_CHAR(DATA,'DD/MM/YYYY') END AS DET_SPC
             , SITUACAO
             , OBSERVACAO
             , CODPARC
            FROM (
                  SELECT DATA, SITUACAO,QTDPENDENCIA, VLRPENDENCIA , OBSERVACAO, NVL(CTT.CODPARC,PAR.CODPARC) AS CODPARC
                   FROM MOTOPRD.AD_TGFSPC SPC
                   LEFT JOIN GROWPRD.TGFPAR PAR ON PAR.CODARTE = SPC.CODPARC
                   LEFT JOIN GROWPRD.PARCTT CTT ON CTT.CODARTE = SPC.CODPARC
                   WHERE NVL(CTT.CODPARC,PAR.CODPARC) = ${codparc}
                   UNION ALL
                  SELECT DATA, SITUACAO,QTDPENDENCIA, VLRPENDENCIA , OBSERVACAO, NVL(CTT.CODPARC,PAR.CODPARC) AS CODPARC
                   FROM RAJAPRD.AD_TGFSPC SPC
                   LEFT JOIN GROWPRD.TGFPAR PAR ON PAR.CODARTE = SPC.CODPARC
                   LEFT JOIN GROWPRD.PARCTT CTT ON CTT.CODARTE = SPC.CODPARC
                   WHERE NVL(CTT.CODPARC,PAR.CODPARC) = ${codparc}
          )SUB
          GROUP BY DECODE(SUB.SITUACAO,'1','Com Pendências','0', 'Sem Pendências','2','Com Pend. Desconsideradas') || CASE WHEN SUB.SITUACAO = '1' THEN   ' - Data: ' || DATA || ', Qtd.: ' || NVL(SUB.QTDPENDENCIA,0) || ', Vlr.: R$ ' || NVL(SUB.VLRPENDENCIA,0)  ELSE '. Data Últ. Consulta: ' || TO_CHAR(DATA,'DD/MM/YYYY') END
                , SITUACAO
                , OBSERVACAO
                , CODPARC
          ORDER BY MAX(DATA) DESC
          FETCH FIRST ROW ONLY
          ) SPC
 WHERE TGFPAR.CODPARC = ${codparc}
`,

    // 2. ficha_credito_grow.jrxml
    getFichaCredito: (codparc) => `
SELECT '9 - MOTO ARTE' AS EMPRESA
        , PAR.CODPARC
        , PAR.NOMEPARC
        , FIN.DTNEG
        , FIN.VLRLIQUIDO
   FROM MOTOPRD.VGFFIN FIN
   INNER JOIN MOTOPRD.TGFPAR PAR ON PAR.CODPARC = FIN.CODPARC
  WHERE FIN.CODTIPTIT = 52
   AND FIN.RECDESP = -1
   AND FIN.DHBAIXA IS NULL
   AND FIN.CODEMP = 9
   AND FIN.CODPARC IN ((SELECT CODARTE FROM TABLE(GROWPRD.AD_GET_PARCEIROS_ERP(${codparc}))))
UNION ALL
  SELECT '1 - MOTO UAI' AS EMPRESA
        , PAR.CODPARC
        , PAR.NOMEPARC
        , FIN.DTNEG
        , FIN.VLRLIQUIDO
   FROM RAJAPRD.VGFFIN FIN
   INNER JOIN RAJAPRD.TGFPAR PAR ON PAR.CODPARC = FIN.CODPARC
  WHERE FIN.CODTIPTIT = 52
   AND FIN.RECDESP = -1
   AND FIN.DHBAIXA IS NULL
   AND FIN.CODEMP = 1
   AND FIN.CODPARC IN ((SELECT CODUAI FROM TABLE(GROWPRD.AD_GET_PARCEIROS_ERP(${codparc}))))
UNION ALL
  SELECT '50 - MOTO FEST' AS EMPRESA
        , PAR.CODFEST AS CODPARC
        , PAR.NOMEPARC
        , FIN.DTNEG
        , FIN.VALOR AS VLRLIQUIDO
      FROM GROWPRD.TGFFIN FIN
      INNER JOIN GROWPRD.TGFPAR PAR ON PAR.CODPARC = FIN.CODPARC
      WHERE FIN.CREDCLIENTE = 'S'
        AND FIN.CODPARC = ${codparc}
        AND NVL(FIN.CONTABANCARIA,' ') <> 'MATRIZ - CAIXA  AUXILIAR'
ORDER BY 1,4
`,

    // 3. ficha_financeiros_grow.jrxml
    getFichaFinanceiros: (codparc) => `
SELECT EMP.CODEMP || ' - ' || EMP.NOMEFANTASIA AS EMPRESA
     , PAR.CODPARC || ' - ' || PAR.NOMEPARC AS NOMEPARC
     , TO_CHAR(FIN.NUMNOTA) AS NUMNOTA
     , FIN.DTNEG
     , FIN.DTVENC
     , FIN.VLRDESDOB
     , CAST(CASE WHEN TRUNC(FIN.DTVENC) < TRUNC(SYSDATE) THEN 1 ELSE 0 END AS FLOAT) VENCIDO
  FROM MOTOPRD.VGFFIN FIN
  INNER JOIN MOTOPRD.TSIEMP EMP ON EMP.CODEMP = FIN.CODEMP
  INNER JOIN MOTOPRD.TGFPAR PAR ON PAR.CODPARC = FIN.CODPARC
WHERE FIN.CODPARC IN ((SELECT CODARTE FROM TABLE(GROWPRD.AD_GET_PARCEIROS_ERP(${codparc}))))
  AND FIN.RECDESP = 1
  AND FIN.DHBAIXA IS NULL
  AND FIN.CODTIPTIT = 4
  AND FIN.CODTIPOPER = 901
UNION ALL
SELECT EMP.CODEMP || ' - ' || EMP.NOMEFANTASIA AS EMPRESA
     , PAR.CODPARC || ' - ' || PAR.NOMEPARC AS NOMEPARC
     , TO_CHAR(FIN.NUMNOTA) AS NUMNOTA
     , FIN.DTNEG
     , FIN.DTVENC
     , FIN.VLRDESDOB
     , CAST(CASE WHEN TRUNC(FIN.DTVENC) < TRUNC(SYSDATE) THEN 1 ELSE 0 END AS FLOAT) VENCIDO
  FROM RAJAPRD.VGFFIN FIN
  INNER JOIN RAJAPRD.TSIEMP EMP ON EMP.CODEMP = FIN.CODEMP
  INNER JOIN RAJAPRD.TGFPAR PAR ON PAR.CODPARC = FIN.CODPARC
WHERE FIN.CODPARC IN ((SELECT CODUAI FROM TABLE(GROWPRD.AD_GET_PARCEIROS_ERP(${codparc}))))
  AND FIN.RECDESP = 1
  AND FIN.DHBAIXA IS NULL
  AND FIN.CODTIPTIT = 4
  AND FIN.CODTIPOPER = 901
UNION ALL
SELECT '50 - MOTO FEST' AS EMPRESA
     , CASE WHEN CTT.CODCTT IS NULL THEN PAR.CODFEST || ' - ' || PAR.NOMEPARC ELSE CTT.CODFEST || ' - ' || CTT.NOMEPARC END AS NOMEPARC
     , FIN.NUMDOC AS NUMNOTA
     , FIN.DTNEG
     , FIN.DTVENC
     , FIN.VALOR AS VLRDESDOB
     , CAST(CASE WHEN TRUNC(FIN.DTVENC) < TRUNC(SYSDATE) THEN 1 ELSE 0 END AS FLOAT) VENCIDO
  FROM GROWPRD.TGFFIN FIN
  INNER JOIN GROWPRD.TGFPAR PAR ON PAR.CODPARC = FIN.CODPARC
   LEFT JOIN GROWPRD.PARCTT CTT ON CTT.CODPARC = FIN.CODPARC AND CTT.CODCTT = FIN.CODCTT
  WHERE FIN.CODPARC = ${codparc}
    AND FIN.CREDCLIENTE = 'N'
    AND NVL(FIN.FORMARECEBIMENTO,'BOLETO')  = 'BOLETO'
ORDER BY 5,2
`,

    // 4. ficha_notas_produtos_grow.jrxml (A de notas detalhadas tem produtos)
    getFichaNotasProdutos: (codparc) => `
WITH SUB2 AS (
SELECT * FROM(
    SELECT  'MOTO ARTE' AS EMPRESA, 9 AS CODEMP, TGFCAB.NUNOTA, TGFCAB.DTNEG, TGFCAB.NUMNOTA
          , TGFTPV.CODTIPVENDA || ' - ' || TGFTPV.DESCRTIPVENDA AS TIPO_NEG, TGFCAB.VLRNOTA
          , TGFVEN.CODVEND || ' - ' || TGFVEN.APELIDO AS VENDEDOR
       FROM MOTOPRD.TGFCAB
       INNER JOIN MOTOPRD.TGFTPV ON TGFTPV.CODTIPVENDA = TGFCAB.CODTIPVENDA AND TGFCAB.DHTIPVENDA = TGFTPV.DHALTER
       INNER JOIN MOTOPRD.TGFVEN ON TGFVEN.CODVEND = TGFCAB.CODVEND
      WHERE TGFCAB.CODTIPOPER = 901 AND TGFCAB.CODPARC IN((SELECT CODARTE FROM TABLE(GROWPRD.AD_GET_PARCEIROS_ERP(${codparc})))) AND TGFCAB.STATUSNOTA = 'L'
    UNION ALL
    SELECT  'MOTO UAI' AS EMPRESA, 1 AS CODEMP, TGFCAB.NUNOTA, TGFCAB.DTNEG, TGFCAB.NUMNOTA
          , TGFTPV.CODTIPVENDA || ' - ' || TGFTPV.DESCRTIPVENDA AS TIPO_NEG, TGFCAB.VLRNOTA
          , TGFVEN.CODVEND || ' - ' || TGFVEN.APELIDO AS VENDEDOR
       FROM RAJAPRD.TGFCAB
       INNER JOIN RAJAPRD.TGFTPV ON TGFTPV.CODTIPVENDA = TGFCAB.CODTIPVENDA AND TGFCAB.DHTIPVENDA = TGFTPV.DHALTER
       INNER JOIN RAJAPRD.TGFVEN ON TGFVEN.CODVEND = TGFCAB.CODVEND
      WHERE TGFCAB.CODTIPOPER = 901 AND TGFCAB.CODPARC IN((SELECT CODUAI FROM TABLE(GROWPRD.AD_GET_PARCEIROS_ERP(${codparc})))) AND TGFCAB.STATUSNOTA = 'L'
    UNION ALL
    SELECT 'MOTO FEST' AS EMPRESA, 50 AS CODEMP, TGFCAB.NUNOTA, TGFCAB.DTNEG, TGFCAB.NUPEDFEST AS NUMNOTA
          , TGFTPV.CODTIPVENDA || ' - ' || TGFTPV.DESCRTIPVENDA AS TIPO_NEG, TGFCAB.VLRNOTA
          , TSIUSU.CODUSU || ' - ' || TSIUSU.NOMEUSU AS VENDEDOR
      FROM GROWPRD.TGFCAB
      INNER JOIN GROWPRD.TGFTPV ON TGFTPV.CODTIPVENDA = TGFCAB.CODTIPVENDA
      INNER JOIN GROWPRD.TSIUSU ON TSIUSU.CODUSU = TGFCAB.CODUSUVEND
      WHERE NUPEDFEST IS NOT NULL AND CODEMP = 50 AND CODPARC = ${codparc}
)SUB
ORDER BY DTNEG DESC
FETCH NEXT 20 ROWS ONLY
)
SELECT SUB2.EMPRESA, SUB2.NUNOTA, SUB2.DTNEG, SUB2.NUMNOTA, SUB2.TIPO_NEG, SUB2.VLRNOTA, SUB2.VENDEDOR
     , TGFPRO.CODPROD || ' - ' || TGFPRO.DESCRPROD AS PRODUTO, CAST(TGFITE.QTDNEG AS INT) AS QTDNEG
     , TGFITE.VLRUNIT, TGFITE.VLRTOT, TGFITE.VLRDESC, TGFITE.VLRTOT - TGFITE.VLRDESC AS VLRLIQ
  FROM SUB2
  INNER JOIN MOTOPRD.TGFITE ON TGFITE.NUNOTA = SUB2.NUNOTA
  INNER JOIN MOTOPRD.TGFPRO ON TGFPRO.CODPROD = TGFITE.CODPROD
 WHERE SUB2.CODEMP = 9
UNION ALL
SELECT SUB2.EMPRESA, SUB2.NUNOTA, SUB2.DTNEG, SUB2.NUMNOTA, SUB2.TIPO_NEG, SUB2.VLRNOTA, SUB2.VENDEDOR
     , TGFPRO.CODPROD || ' - ' || TGFPRO.DESCRPROD AS PRODUTO, CAST(TGFITE.QTDNEG AS INT) AS QTDNEG
     , TGFITE.VLRUNIT, TGFITE.VLRTOT, TGFITE.VLRDESC, TGFITE.VLRTOT - TGFITE.VLRDESC AS VLRLIQ
  FROM SUB2
  INNER JOIN RAJAPRD.TGFITE ON TGFITE.NUNOTA = SUB2.NUNOTA
  INNER JOIN RAJAPRD.TGFPRO ON TGFPRO.CODPROD = TGFITE.CODPROD
 WHERE SUB2.CODEMP = 1
UNION ALL
SELECT SUB2.EMPRESA, SUB2.NUNOTA, SUB2.DTNEG, SUB2.NUMNOTA, SUB2.TIPO_NEG, SUB2.VLRNOTA, SUB2.VENDEDOR
     , TGFPRO.CODPROD || ' - ' || TGFPRO.DESCRPROD AS PRODUTO, CAST(TGFITE.QTDNEG AS INT) AS QTDNEG
     , TGFITE.VLRUNIT, TGFITE.VLRTOT, TGFITE.VLRDESC, TGFITE.VLRTOT - TGFITE.VLRDESC AS VLRLIQ
  FROM SUB2
  INNER JOIN GROWPRD.TGFITE ON TGFITE.NUNOTA = SUB2.NUNOTA
  INNER JOIN GROWPRD.TGFPRO ON TGFPRO.CODPROD = TGFITE.CODPROD
 WHERE SUB2.CODEMP = 50
 ORDER BY EMPRESA, DTNEG DESC
`,

    // 5. ficha_produtos_grow.jrxml
    getFichaProdutos: (codparc) => `
SELECT * FROM(
    SELECT * FROM(
            SELECT 'MOTO ARTE' AS EMPRESA, SUB.CODPROD || ' - ' || SUB.DESCRPROD AS DESCRPROD, SUB.QTDNEG, MAX(TGFITE.VLRUNIT) AS VLRUNIT
              FROM (
            SELECT TGFPRO.CODPROD, TGFPRO.DESCRPROD, SUM(QTDNEG) AS QTDNEG, MAX(TGFITE.NUNOTA) AS NUNOTA
               FROM MOTOPRD.TGFCAB
               INNER JOIN MOTOPRD.TGFITE ON TGFITE.NUNOTA = TGFCAB.NUNOTA
               INNER JOIN MOTOPRD.TGFPRO ON TGFPRO.CODPROD = TGFITE.CODPROD
              WHERE TGFCAB.CODTIPOPER = 901 AND TGFCAB.CODPARC IN((SELECT CODARTE FROM TABLE(GROWPRD.AD_GET_PARCEIROS_ERP(${codparc})))) AND TGFCAB.STATUSNOTA = 'L'
            GROUP BY  TGFPRO.CODPROD, TGFPRO.DESCRPROD
            ORDER BY 3 DESC FETCH NEXT 20 ROWS ONLY
            ) SUB
            INNER JOIN MOTOPRD.TGFITE ON TGFITE.NUNOTA = SUB.NUNOTA AND TGFITE.CODPROD = SUB.CODPROD
            GROUP BY SUB.CODPROD || ' - ' || SUB.DESCRPROD, SUB.QTDNEG
            UNION ALL
            SELECT 'MOTO UAI' AS EMPRESA, SUB.CODPROD || ' - ' || SUB.DESCRPROD AS DESCRPROD, SUB.QTDNEG, MAX(TGFITE.VLRUNIT) AS VLRUNIT
              FROM (
            SELECT TGFPRO.CODPROD, TGFPRO.DESCRPROD, SUM(QTDNEG) AS QTDNEG, MAX(TGFITE.NUNOTA) AS NUNOTA
               FROM RAJAPRD.TGFCAB
               INNER JOIN RAJAPRD.TGFITE ON TGFITE.NUNOTA = TGFCAB.NUNOTA
               INNER JOIN RAJAPRD.TGFPRO ON TGFPRO.CODPROD = TGFITE.CODPROD
              WHERE TGFCAB.CODTIPOPER = 901 AND TGFCAB.CODPARC IN((SELECT CODUAI FROM TABLE(GROWPRD.AD_GET_PARCEIROS_ERP(${codparc})))) AND TGFCAB.STATUSNOTA = 'L'
            GROUP BY  TGFPRO.CODPROD, TGFPRO.DESCRPROD
            ORDER BY 3 DESC FETCH NEXT 20 ROWS ONLY
            ) SUB
            INNER JOIN RAJAPRD.TGFITE ON TGFITE.NUNOTA = SUB.NUNOTA AND TGFITE.CODPROD = SUB.CODPROD
            GROUP BY SUB.CODPROD || ' - ' || SUB.DESCRPROD, SUB.QTDNEG
            UNION ALL
            SELECT 'MOTO FEST' AS EMPRESA, SUB.CODPROD || ' - ' || SUB.DESCRPROD AS DESCRPROD, SUB.QTDNEG, MAX(ITE.VLRUNIT) AS VLRUNIT
              FROM(
                SELECT PRO.CODPROD, PRO.DESCRPROD, SUM(QTDNEG) AS QTDNEG, MAX(ITE.NUNOTA) AS NUNOTA
                  FROM GROWPRD.TGFCAB CAB
                  INNER JOIN GROWPRD.TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
                  INNER JOIN GROWPRD.TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD
                 WHERE CAB.CODEMP = 50 AND CAB.CODPARC = ${codparc}
                GROUP BY  PRO.CODPROD, PRO.DESCRPROD
                ORDER BY 3 DESC FETCH NEXT 20 ROWS ONLY
            ) SUB
            INNER JOIN GROWPRD.TGFITE ITE ON ITE.NUNOTA = SUB.NUNOTA AND ITE.CODPROD = SUB.CODPROD
            GROUP BY SUB.CODPROD || ' - ' || SUB.DESCRPROD, SUB.QTDNEG
    )ORDER BY QTDNEG DESC FETCH NEXT 20 ROW ONLY
)SUB2 ORDER BY EMPRESA, QTDNEG DESC
`,

    // 6. ficha_vendas_periodo_grow.jrxml
    getFichaVendasPeriodo: (codparc) => `
SELECT * FROM (
    SELECT MES, ANO, ANO_MES, SUM(VLRFATUR) AS VLRFATUR
     FROM(
            SELECT EXTRACT(MONTH FROM TGFCAB.DTFATUR) AS MES, EXTRACT(YEAR FROM TGFCAB.DTFATUR) AS ANO
                 , RTRIM(LTRIM(SUBSTR(TO_CHAR(TGFCAB.DTFATUR,'MONTH'),0,3))) ||'/' ||EXTRACT(YEAR FROM TGFCAB.DTFATUR) AS ANO_MES, TGFCAB.VLRNOTA AS VLRFATUR
             FROM MOTOPRD.TGFCAB
             WHERE TGFCAB.CODTIPOPER = 901 AND TGFCAB.STATUSNOTA = 'L' AND TGFCAB.CODPARC IN ((SELECT CODARTE FROM TABLE(GROWPRD.AD_GET_PARCEIROS_ERP(${codparc}))))
            UNION ALL
            SELECT EXTRACT(MONTH FROM TGFCAB.DTFATUR) AS MES, EXTRACT(YEAR FROM TGFCAB.DTFATUR) AS ANO
                 , RTRIM(LTRIM(SUBSTR(TO_CHAR(TGFCAB.DTFATUR,'MONTH'),0,3))) ||'/' ||EXTRACT(YEAR FROM TGFCAB.DTFATUR) AS ANO_MES, TGFCAB.VLRNOTA AS VLRFATUR
             FROM RAJAPRD.TGFCAB
             WHERE TGFCAB.CODTIPOPER = 901 AND TGFCAB.STATUSNOTA = 'L' AND TGFCAB.CODPARC IN ((SELECT CODUAI FROM TABLE(GROWPRD.AD_GET_PARCEIROS_ERP(${codparc}))))
            UNION ALL
            SELECT EXTRACT(MONTH FROM TGFCAB.DTNEG) AS MES, EXTRACT(YEAR FROM TGFCAB.DTNEG) AS ANO
                 , RTRIM(LTRIM(SUBSTR(TO_CHAR(TGFCAB.DTNEG,'MONTH'),0,3))) ||'/' ||EXTRACT(YEAR FROM TGFCAB.DTNEG) AS ANO_MES, TGFCAB.VLRNOTA AS VLRFATUR
             FROM GROWPRD.TGFCAB
             WHERE TGFCAB.NUPEDFEST IS NOT NULL AND TGFCAB.CODEMP = 50 AND TGFCAB.CODPARC = ${codparc}
    )SUB
    GROUP BY MES, ANO, ANO_MES
    ORDER BY 2 DESC FETCH FIRST 12 ROWS ONLY
)DADOS ORDER BY 2,1
`,

    // 7. ficha_vinculados_grow.jrxml
    getFichaVinculados: (codparc) => `
SELECT CTT.CODPARC
     , CTT.CODCTT
     , CTT.CGCCPF
     , CTT.NOMEPARC
     , CTT.CODARTE
     , CTT.CODUAI
     , CTT.CODFEST
     , CASE WHEN NVL(CTT.SIMPLES,'N') = 'S' THEN 'Sim' ELSE 'Não' END AS SIMPLES_GROW
     , CASE WHEN NVL(P2.SIMPLES,'N') = 'S' THEN 'Sim' ELSE 'Não' END AS SIMPLES_ARTE
     , CASE WHEN NVL(P3.SIMPLES,'N') = 'S' THEN 'Sim' ELSE 'Não' END AS SIMPLES_UAI
  FROM GROWPRD.PARCTT CTT
   LEFT JOIN MOTOPRD.TGFPAR P2 ON P2.CODPARC = CTT.CODARTE
   LEFT JOIN RAJAPRD.TGFPAR P3 ON P3.CODPARC = CTT.CODUAI
  WHERE CTT.CODPARC = ${codparc}
`
};
